# Generated by Django 5.0.3 on 2024-04-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='writers.writer')),
                ('biography', models.TextField()),
            ],
        ),
    ]
