# Generated by Django 5.0.3 on 2024-05-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_tags_post_post_tags'),
        ('writers', '0002_writerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writers.writer'),
        ),
    ]
