# Generated by Django 5.0.3 on 2024-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
